---
- name: Automate SNOW 
  hosts: localhost
  connection: local
  collections:
    - servicenow.itsm
    
  vars:
    demo_username: "{{ lookup('env', 'SN_USERNAME') }}"
    incident_list: []

  tasks:

    - name: find user created incidents
      servicenow.itsm.incident_info:
        query:
          - sys_created_by: LIKE {{ demo_username }}
            active: = true
      register: incidents

    - name: query incident number and creation time 
      set_fact:
        incident_list: '{{ incident_list + [{"number": item.number, "opened_at": item.opened_at}] }}'
      loop: "{{ incidents.records }}"
      when: incidents

    - name: Create a problem from incident
      servicenow.itsm.problem:
        short_description: "The website is completely down!!!!"
        description: "{{ lookup('env', 'SN_USERNAME') }} created a new problem"
      register: problem

    - name: Assign a problem to a user for assessment
      servicenow.itsm.problem:
        number: "{{ problem.record.number }}"
        state: 1
        assigned_to: "{{ lookup('env', 'SN_USERNAME') }}"

    - name: Update incident status now that problem has been created
      servicenow.itsm.incident:
        number: "{{ item.number }}"
        state: in_progress
        other:
          problem_id: "{{ problem.record.number }}"
      loop: "{{ incident_list }}"

    - debug:
        msg: "A new problem has been created {{ problem.record.number }}"
